# -------------------------------------------------- #
# This file is autogenerated by pioasm; do not edit! #
# -------------------------------------------------- #

import rp2
from machine import Pin
# ------- #
# blinker #
# ------- #

blinker_FREQUENCY = 2500

@rp2.asm_pio(out_shiftdir=rp2.PIO.SHIFT_RIGHT, fifo_join=rp2.PIO.JOIN_TX)
def blinker():
    set(pindirs, 1)                  [16] # 0
    set(pins, 0)                          # 1
    pull(block)                           # 2
    mov(x, osr)                           # 3
    wrap_target()
    set(pins, 1)                          # 4
    set(y, 8)                        [23] # 5
    label("6")
    jmp(y_dec, "6")                  [24] # 6
    set(pins, 0)                          # 7
    set(y, 8)                        [22] # 8
    label("9")
    jmp(y_dec, "9")                  [24] # 9
    jmp(x_dec, "11")                      # 10
    label("11")
    set(y, 31)                       [1]  # 11
    label("12")
    nop()                            [13] # 12
    nop()                            [31] # 13
    jmp(y_dec, "12")                 [31] # 14
    mov(x, osr)                           # 15
    pull(noblock)                         # 16
    wrap()


