[target.'cfg(target_os = "vexos")']
rustflags = ["-Clink-arg=-Tvexide.ld", "--cfg", "getrandom_backend=\"extern_impl\""]

[unstable]
build-std = ["std", "panic_abort"]
build-std-features = ["compiler-builtins-mem"]
